name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Run Vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 1085a57da0725c19e19586025438e8c16f34c890

    - run: $VCPKG_ROOT/vcpkg install openimageio[ffmpeg,libraw]:x64-linux

    - run: $VCPKG_ROOT/vcpkg install opencolorio:x64-linux

    - run: sudo apt-get install libxmu-dev libxi-dev libgl-dev

    - run: sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

    - run: $VCPKG_ROOT/vcpkg install glew:x64-linux

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
