name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: get-cmake
      uses: lukka/get-cmake@v3.21.1
    
    - name: Run Vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 1085a57da0725c19e19586025438e8c16f34c890

    - name: Install OpenImageIO
      run: ${{env.VCPKG_ROOT}}/vcpkg.exe install openimageio[ffmpeg,libraw]:x64-windows --recurse
    
    - name: Install OpenColorIO
      run: ${{env.VCPKG_ROOT}}/vcpkg.exe install opencolorio:x64-windows

    - name: Install Glew
      run: ${{env.VCPKG_ROOT}}/vcpkg.exe install glew:x64-windows
    
    - name: Install GLFW
      run: ${{env.VCPKG_ROOT}}/vcpkg.exe install glfw3:x64-windows

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
